mix: Remove `hsPkgs` from flake packages
Because, it is not really a derivation:

```
❯ nix build github:JonathanLorimer/htmx#hsPkgs
error: expected flake output attribute 'packages.x86_64-linux.hsPkgs' to be a derivation or path but found a set: { "2captcha" = «thunk»; "3d-graphics-examples" = «thunk»; "3dmodels" = «thunk»; "4Blocks" = «thunk»; AAI = «thunk»; ABList = «thunk»; AC-Angle = «thunk»; AC-Boolean = «thunk»; AC-BuildPlatform = «thunk»; AC-Colour = «thunk»; «18180 attributes elided» }
```